# Generated by Django 6.1 on 2026-08-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fcc499Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filer_id', models.CharField(db_index=True, help_text='499 Filer ID from the FCC record', max_length=20, unique=True)),
                ('legal_name', models.CharField(db_index=True, max_length=500)),
                ('doing_business_as', models.CharField(blank=True, max_length=500, null=True)),
                ('usf_contributor', models.CharField(blank=True, max_length=20, null=True)),
                ('cores_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('registration_current_as_of', models.CharField(blank=True, max_length=50, null=True)),
                ('headquarters_address', models.CharField(blank=True, max_length=500, null=True)),
                ('headquarters_city', models.CharField(blank=True, max_length=150, null=True)),
                ('headquarters_state', models.CharField(blank=True, max_length=50, null=True)),
                ('headquarters_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fcc_registration_information', models.CharField(blank=True, max_length=255, null=True)),
                ('search_company_name', models.CharField(db_index=True, help_text='The company name that was searched to find this filing', max_length=500)),
                ('search_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail_url', models.URLField(blank=True, help_text='Official FCC Form 499 detail page for this filer', max_length=1000, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['legal_name'],
                'indexes': [models.Index(fields=['legal_name'], name='fcc499_fcc4_legal_n_f573fa_idx'), models.Index(fields=['filer_id'], name='fcc499_fcc4_filer_i_81b677_idx'), models.Index(fields=['search_company_name'], name='fcc499_fcc4_search__3b4499_idx')],
            },
        ),
    ]
