# Generated by Django 6.1 on 2026-08-21 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_simplify_to_unique_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('date_opened', models.DateField()),
                ('problem', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('noc_notified', models.BooleanField(default=False)),
                ('customer_notified', models.BooleanField(default=False)),
                ('resolution_comments', models.TextField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trouble_tickets', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
