# Generated by Django 6.1 on 2026-08-21 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_simplify_to_unique_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('agreement_title', models.CharField(max_length=255)),
                ('agreement_type', models.CharField(choices=[('customer_agreement', 'Customer Agreement'), ('carrier_agreement', 'Carrier Agreement'), ('service_agreement', 'Service Agreement'), ('compliance_agreement', 'Compliance Agreement'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='agreements/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('notes', models.TextField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='customers.customer')),
                ('previous_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='agreements.agreement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
