# Generated by Django 6.1 on 2026-08-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_in_db_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['carrier'],
                'indexes': [models.Index(fields=['carrier'], name='customers_c_carrier_252ad6_idx'), models.Index(fields=['country'], name='customers_c_country_fc020b_idx')],
                'constraints': [models.UniqueConstraint(fields=('carrier', 'country'), name='unique_carrier_country')],
            },
        ),
    ]
