# Generated by Django 6.1 on 2026-08-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_simplify_to_unique_carrier'),
        ('fcc499', '0001_initial'),
        ('rmd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='linked_fcc_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fcc499.fcc499filing'),
        ),
        migrations.AddField(
            model_name='customer',
            name='linked_rmd_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rmd.rmdfiling'),
        ),
    ]
