# Generated by Django 6.1 on 2026-08-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_simplify_to_unique_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateRegistryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('flagged', 'Flagged'), ('needs_review', 'Needs Review'), ('verification_failed', 'Verification Failed')], default='pending', max_length=20)),
                ('weekly_check_status', models.CharField(choices=[('pending', 'Pending'), ('checked', 'Checked'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pass_flagged', models.CharField(blank=True, choices=[('passed', 'Passed'), ('flagged', 'Flagged')], max_length=20, null=True)),
                ('escalation_status', models.CharField(choices=[('no_escalation', 'No Escalation'), ('alert_created', 'Alert Created'), ('pending_review', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='no_escalation', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('frn', models.CharField(blank=True, max_length=50, null=True)),
                ('filer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('rmd_status', models.CharField(blank=True, max_length=20, null=True)),
                ('fcc_status', models.CharField(blank=True, max_length=20, null=True)),
                ('frn_match_status', models.CharField(blank=True, max_length=30, null=True)),
                ('operational_status', models.CharField(blank=True, max_length=20, null=True)),
                ('flag_reasons', models.JSONField(blank=True, default=list)),
                ('change_detected', models.BooleanField(default=False)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('current_snapshot', models.JSONField(blank=True, null=True)),
                ('previous_snapshot', models.JSONField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registry_record', to='customers.customer')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('registry_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='intermediate_registry.intermediateregistryrecord')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
