# Generated by Django 6.1 on 2026-08-25 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intermediate_registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='change_detected',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='country',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='current_snapshot',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='escalation_status',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='fcc_status',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='filer_id',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='flag_reasons',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='frn',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='frn_match_status',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='last_reviewed',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='operational_status',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='pass_flagged',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='previous_snapshot',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='rmd_status',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='intermediateregistryrecord',
            name='weekly_check_status',
        ),
        migrations.AddField(
            model_name='intermediateregistryrecord',
            name='match_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='intermediateregistryrecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('not_present', 'Not Present'), ('review_required', 'Review Required')], default='not_present', max_length=20),
        ),
        migrations.CreateModel(
            name='IntermediateRegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(db_index=True, max_length=500)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('regulatory_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('regulatory_contact_title', models.CharField(blank=True, max_length=255, null=True)),
                ('regulatory_contact_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('regulatory_contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['business_name'], name='intermediat_busines_5ac255_idx')],
            },
        ),
        migrations.AddField(
            model_name='intermediateregistryrecord',
            name='matched_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='intermediate_registry.intermediateregistryentry'),
        ),
        migrations.DeleteModel(
            name='RegistryAlert',
        ),
    ]
