# Generated by Django 6.1 on 2026-08-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intermediate_registry', '0002_remove_intermediateregistryrecord_change_detected_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intermediateregistryrecord',
            options={'ordering': ['registry_id']},
        ),
    ]
