# Generated by Django 6.1 on 2026-08-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intermediate_registry', '0003_alter_intermediateregistryrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediateregistryrecord',
            name='change_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intermediateregistryrecord',
            name='changes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='intermediateregistryrecord',
            name='current_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intermediateregistryrecord',
            name='previous_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
