# Generated by Django 6.1 on 2026-08-25 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intermediate_registry', '0004_intermediateregistryrecord_change_detected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(default='Intermediate Registry', max_length=50)),
                ('verification_result', models.CharField(choices=[('present', 'Present'), ('not_present', 'Not Present'), ('review_required', 'Review Required')], max_length=20)),
                ('issue', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registry_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='intermediate_registry.intermediateregistryrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
