# Generated by Django 6.1 on 2026-08-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdocument',
            name='document_type',
        ),
    ]
