# Generated by Django 6.1 on 2026-08-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('document', 'Document'), ('tech_form', 'Tech Form')], default='document', max_length=20),
        ),
    ]
