# Generated by Django 6.1 on 2026-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RmdFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, help_text='RMD identifier, e.g. RMD0001410', max_length=32, unique=True)),
                ('sys_id', models.CharField(blank=True, db_index=True, help_text='ServiceNow sys_id parsed from filing_url', max_length=64, null=True, unique=True)),
                ('frn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('foreign_voice_provider', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('other_frns', models.TextField(blank=True, null=True)),
                ('other_dba_names', models.TextField(blank=True, null=True)),
                ('previous_dba_names', models.TextField(blank=True, null=True)),
                ('robocall_mitigation_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_department', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_business_address', models.TextField(blank=True, null=True)),
                ('contact_country', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_telephone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('implementation', models.CharField(blank=True, max_length=255, null=True)),
                ('voice_service_provider_choice', models.CharField(blank=True, max_length=10, null=True)),
                ('gateway_provider_choice', models.CharField(blank=True, max_length=10, null=True)),
                ('intermediate_provider_choice', models.CharField(blank=True, max_length=10, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('last_recertified', models.DateField(blank=True, null=True)),
                ('filing_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_in_db_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['business_name'],
                'indexes': [models.Index(fields=['business_name'], name='rmd_rmdfili_busines_cbe954_idx'), models.Index(fields=['frn'], name='rmd_rmdfili_frn_d9f793_idx'), models.Index(fields=['number'], name='rmd_rmdfili_number_688fcf_idx')],
            },
        ),
    ]
